### PR TITLE
CMake Package Config now supported retry

### PR DESCRIPTION
**Pull request by ahundt**
should be same as #5 or close to it

### CODE REVIEW

**Comment by ahundt** [comment]
@gergondet @haudren seems installation script for pybindgen may be the problem?

```

$ curDir=`pwd`; cd "$build_dir"; wget https://pybindgen.googlecode.com/files/pybindgen-0.16.0.tar.bz2; tar -xvjf ./pybindgen-0.16.0.tar.bz2; cd pybindgen-0.16.0; ./waf configure; ./waf; sudo ./waf install; cd $curDir
--2017-01-24 08:03:29--  https://pybindgen.googlecode.com/files/pybindgen-0.16.0.tar.bz2
Resolving pybindgen.googlecode.com (pybindgen.googlecode.com)... 74.125.69.82, 2607:f8b0:4001:c08::52
Connecting to pybindgen.googlecode.com (pybindgen.googlecode.com)|74.125.69.82|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-24 08:03:29 ERROR 404: Not Found.

tar (child): ./pybindgen-0.16.0.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/home/travis/build.sh: line 57: cd: pybindgen-0.16.0: No such file or directory
/home/travis/build.sh: line 57: ./waf: No such file or directory
/home/travis/build.sh: line 57: ./waf: No such file or directory
sudo: ./waf: command not found
```

**Comment by ahundt** [comment]
Oh also I made sure you guys have write access on this pull request so you can modify it directly if that helps.

**Comment by gergondet** [comment]
I changed the URL for pybindgen archive in jrl-travis. I've update the subtree in your branch, let's wait and see

**Comment by gergondet** [comment]
Ok, it finally went through after a few more tweaks. Merging now, thanks for the contribution :cake:

**Comment by ahundt** [comment]
Glad it is working now, thanks for the tweaks and the libraries!l

**Pull request merged**
