### PR TITLE
Topic/cython

### PR DESCRIPTION
**Pull request by gergondet**
This PR moves the bindings from a pybdingen solution to a Cython solution.

The benefits/changes are:
- native conversion to/from numpy arrays (no shared memory)
- support operations between Eigen objects and return Eigen objects according to the operation
- slice access to Eigen objects (returns a copy of the "slice")
- add bindings for `Eigen::AngleAxisd` (minimal: construction and conversion to matrix)

A cmake script is provided to build the bindings in CI setting but the recommended manual way is to go simply use the `setup.py` script

@haudren FYI, this PR includes topic/useCythonMemoryView

### CODE REVIEW

**Comment by haudren** [comment]
Nice! I would maybe add a small warning that the Eigen <-> Numpy can be expensive at big sizes because of the change in storage orders.

Reminder of the times:
```python
>>> import numpy as np
>>> import eigen

>>> A = np.random.random((2000, 50))
>>> B = eigen.MatrixXd(A)
>>> %timeit eigen.MatrixXd(A)
10000 loops, best of 3: 107 µs per loop
>>> timeit np.array(B)
10000 loops, best of 3: 53.1 µs per loop
```

**Comment by haudren** [comment]
Oh and it might be nice to slightly rebase before merging ;)

**Comment by ahundt** [comment]
Wow ~20k fewer lines?! that's impressive

**Comment by gergondet** [comment]
I've added some info on the timing.

> Oh and it might be nice to slightly rebase before merging ;)

I will "Squash and merge" as I find this leads to the cleanest tree in the end.

> Wow ~20k fewer lines?! that's impressive

The bulk of it is probably from the removal of the `cmake` folder. Cython tends to be more verbose than pybindgen unfortunately.

**Comment by haudren** [comment]
Unfortunately yes :( But I don't think it would have been possible to do an as efficient numpy conversion in pure pybindgen.

**Comment by ahundt** [comment]
ah I see, nonetheless thanks for adding this!

**Pull request merged**
